<div class="col-lg-12">
    <div class="page-header">
        <h2><span class="glyphicon glyphicon-list-alt"></span>Zoznam prístupových kódov</h2>
        <a href="<?php echo $this->url('accesscodes', array('action' => 'add')); ?>" class="btn btn-info pull-right"><span class="glyphicon glyphicon-plus"></span> Pridať</a>
        <div class="person-type-selector pull-right">
            <?php
                $form = $this->activeInactiveForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formElement($form->get('typ'));
                echo $this->form()->closeTag(); 
            ?>
        </div>
    </div>
    <?php if(isset($this->successMessage) && !empty($this->successMessage)) : ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><?php echo $this->successMessage; ?></strong>
    </div>
    <?php endif; ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Prístupový kód</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach((isset($this->codes)) ? $this->codes : array() as $code) : ?>
            <tr>
                <td>
                    <?php echo $code->code ?>
                    <?php if(!is_null($code->refPerson)) : ?>
                        <span class="glyphicon glyphicon-exclamation-sign"></span>
                    <?php endif; ?>
                </td>
                <td>
                    <?php if($this->actualCodeType) : ?>
                        <a href="<?php echo $this->url('accesscodes', array('action' => 'deactivate', 'id' => $code->id)); ?>" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove glyphicon-no-padding"></span></a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('accesscodes', array('action' => 'activate', 'id' => $code->id)); ?>" class="btn btn-info pull-right"><span class="glyphicon glyphicon-ok glyphicon-no-padding"></span></a>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('accesscodes', array('action' => 'edit', 'id' => $code->id)); ?>" class="btn btn-default pull-right"><span class="glyphicon glyphicon-pencil glyphicon-no-padding"></span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>