<div class="col-lg-6">
    <div class="row">
        <div class="page-header">
            <h2><span class="glyphicon glyphicon-pencil"></span>Upraviť miestnosť</h2>
        </div>
        <?php 
            $form = $this->form;
            $form->prepare();
            echo $this->form()->openTag($form);
            $this->formHelper()->formItem($form, 'label');
            $this->formHelper()->formItem($form, 'title');
            $this->formHelper()->formItem($form, 'designation');
            $this->formHelper()->formSubmit($form, 'submit-update');
            echo $this->form()->closeTag(); 
        ?>
    </div>
</div>