<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Evidencia pracovníkov KRIS</title>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.css')) 
        ?>
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300,300italic,400italic,600italic,700italic&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
        
    </head>
    <body>
        <div class="header">
            <div class="container">
                <div class="col-lg-12">
                    <h2><span class="glyphicon glyphicon-time"></span>Evidencia pracovníkov KRIS</h2>
                    <p>Semestrálna práca z predmenu AVPJ. Zadanie: Systém na evidenciu prítomnosti pracovníkov KRIS.</p>
                </div>
            </div>
        </div>
        <?php if($this->layoutHelper()->isLogged()) : ?>
            <div class="admin-panel">
                <div class="container">
                    <div class="col-lg-12">
                        <span class="admin-panel-title">Administrácia:</span>
                        <a href="<?php echo $this->url('room', array('action' => 'list')); ?>" class="btn btn-info"><span class="glyphicon glyphicon-edit"></span> Miestnosti</a>
                        <a href="<?php echo $this->url('person', array('action' => 'list')); ?>" class="btn btn-info"><span class="glyphicon glyphicon-user"></span> Pracovníci</a>
                        <a href="<?php echo $this->url('accesscodes', array('action' => 'list')); ?>" class="btn btn-info"><span class="glyphicon glyphicon-qrcode"></span> Prístupové kódy</a>
                        <a href="<?php echo $this->url('accessright'); ?>" class="btn btn-info"><span class="glyphicon glyphicon-lock"></span> Prístupové práva</a>
                        <a href="<?php echo $this->url('accesslog'); ?>" class="btn btn-info"><span class="glyphicon glyphicon-book"></span> Záznamy</a>
                        <a href="<?php echo $this->url('administration', array('action' => 'logout')); ?>" class="btn btn-warning pull-right"><span class="glyphicon glyphicon-log-out"></span> Odhlásiť</a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
