<div class="col-lg-12">
    <div class="page-header">
        <h2><span class="glyphicon glyphicon-list-alt"></span>Záznamy prístupov</h2>
    </div>
    
    <?php
        $filterForm = $this->filterForm;
        $filterForm->prepare();
        echo $this->form()->openTag($filterForm);
    ?>
    <div class="col-lg-3"><?php echo $this->formElement($filterForm->get('person-select')); ?></div>
    <div class="col-lg-3"><?php echo $this->formElement($filterForm->get('room-select')); ?></div>
    <div class="col-lg-2"><?php echo $this->formElement($filterForm->get('date-begin')); ?></div>
    <div class="col-lg-2"><?php echo $this->formElement($filterForm->get('date-end')); ?></div>
    <div class="col-lg-2"><?php echo $this->formElement($filterForm->get('filter-submit')); ?></div>
    <?php
        echo $this->form()->closeTag(); 
    ?>
    
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Pracovník</th>
                <th>Prístupový kód</th>
                <th>Miestnosť</th>
                <th>Vstup / Odchod</th>
                <th>Časová pečiatka</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach((isset($this->logs)) ? $this->logs : array() as $log) : ?>
            <tr>
                <td><?php echo $log['person']; ?></td>
                <td><?php echo $log['code']; ?></td>
                <td><strong><?php echo $log['room']; ?></strong></td>
                <td><?php echo ($log['entryType'] == 1) ? "Príchod" : "Odchod"; ?></td>
                <td><?php echo $log['timestamp']; ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>