<div class="col-lg-5">
    <div class="row">
        <div class="page-header">
            <h2><span class="glyphicon glyphicon-user"></span>Administrácia</h2>
        </div>
        <?php 
            $loginForm = $this->loginForm;
            $loginForm->prepare();
            echo $this->form()->openTag($loginForm);
        ?>
        <div class="form-group">
            <div class="col-lg-3 control-label">
                <?php echo $this->formLabel($loginForm->get('login')); ?>
            </div>
            <div class="col-lg-9">
                <?php echo $this->formElement($loginForm->get('login')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3 control-label">
                <?php echo $this->formLabel($loginForm->get('password')); ?>
            </div>
            <div class="col-lg-9">
                <?php echo $this->formElement($loginForm->get('password')); ?>
            </div>
        </div>  
        <div class="form-group">
            <div class="col-lg-3 pull-right">
                <?php echo $this->formSubmit($loginForm->get('submit')); ?>
            </div>
        </div>
        <?php 
            echo $this->form()->closeTag(); 
        ?>
    </div>
</div>
<div class="col-lg-5 pull-right">
    <div class="row">
        <div class="page-header">
            <h2><span class="glyphicon glyphicon-phone"></span>Terminál</h2>
        </div>
        <?php 
            $terminalForm = $this->terminalForm;
            $terminalForm->prepare();
            echo $this->form()->openTag($terminalForm);
        ?>
        
        <?php if(!empty($this->message)) : ?>
            <div class="alert <?php echo ($this->errorMessage) ? 'alert-danger' : 'alert-success'; ?> alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <strong><?php echo $this->message; ?></strong>
            </div>
        <?php endif; ?>
        
        <div class="form-group">
            <div class="col-lg-3 control-label">
                <?php echo $this->formLabel($terminalForm->get('room')); ?>
            </div>
            <div class="col-lg-9">
                <?php echo $this->formElement($terminalForm->get('room')); ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3 control-label">
                <?php echo $this->formLabel($terminalForm->get('code')); ?>
            </div>
            <div class="col-lg-9">
                <?php echo $this->formElement($terminalForm->get('code')); ?>
            </div>
        </div>  
        <div class="form-group">
            <div class="col-lg-3 pull-right">
                <?php echo $this->formSubmit($terminalForm->get('submit-enter')); ?>
            </div>
            <div class="col-lg-3 pull-right">
                <?php echo $this->formSubmit($terminalForm->get('submit-leave')); ?>
            </div>
        </div>
        <?php 
            echo $this->form()->closeTag(); 
        ?>
    </div>
</div>
