<div class="col-lg-12">
    <div class="page-header">
        <h2><span class="glyphicon glyphicon-list-alt"></span>Zoznam pracovníkov</h2>
        <a href="<?php echo $this->url('person', array('action' => 'add')); ?>" class="btn btn-info pull-right"><span class="glyphicon glyphicon-plus"></span> Pridať</a>
        <div class="person-type-selector pull-right">
            <?php
                $form = $this->personActiveForm;
                $form->prepare();
                echo $this->form()->openTag($form);
                echo $this->formElement($form->get('typ'));
                echo $this->form()->closeTag(); 
            ?>
        </div>
    </div>
    <?php if(isset($this->successMessage) && !empty($this->successMessage)) : ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong><?php echo $this->successMessage; ?></strong>
    </div>
    <?php endif; ?>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Pracovník</th>
                <th>Osobný kód</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach((isset($this->persons)) ? $this->persons : array() as $person) : ?>
            <tr>
                <td><?php echo "$person->titleBefore $person->firstName <strong>$person->lastName</strong>"; echo ($person->titleBehind != "") ? ", $person->titleBehind" : ""; ?></td>
                <td><?php echo (isset($this->codes[strval($person->id)])) ? $this->codes[strval($person->id)] : ""; ?></td>
                <td>
                    <?php if($this->actualPersonType) : ?>
                        <a href="<?php echo $this->url('person', array('action' => 'deactivate', 'id' => $person->id)); ?>" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove glyphicon-no-padding"></span></a>
                    <?php else : ?>
                        <a href="<?php echo $this->url('person', array('action' => 'activate', 'id' => $person->id)); ?>" class="btn btn-info pull-right"><span class="glyphicon glyphicon-ok glyphicon-no-padding"></span></a>
                    <?php endif; ?>
                    <a href="<?php echo $this->url('person', array('action' => 'edit', 'id' => $person->id)); ?>" class="btn btn-default pull-right"><span class="glyphicon glyphicon-pencil glyphicon-no-padding"></span></a>
                    <a href="<?php echo $this->url('person', array('action' => 'add-access-right', 'id' => $person->id)); ?>" class="btn btn-info pull-right"><span class="glyphicon glyphicon-lock glyphicon-no-padding"></span></a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>